/**
 * eventTypes.js
 * Centralized list of all events in the system.
 */
module.exports = {
  // Order Events
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_UPDATED: 'ORDER_UPDATED',
  ORDER_DELETED: 'ORDER_DELETED',
  ORDER_PAID: 'ORDER_PAID',
  ORDER_RENEWED: 'ORDER_RENEWED',
  IMPORT_ORDER_CREATED: 'IMPORT_ORDER_CREATED',

  // Refund Credit Events
  REFUND_CREDIT_UPDATED: 'REFUND_CREDIT_UPDATED',

  // Cron Events
  DAILY_FOUR_DAYS_DUE: 'DAILY_FOUR_DAYS_DUE',
  DAILY_ZERO_DAYS_DUE: 'DAILY_ZERO_DAYS_DUE',

  // Finance Events
  FINANCE_MONTHLY_DELTA_CHANGED: 'FINANCE_MONTHLY_DELTA_CHANGED',
  SEPAY_WEBHOOK_RECEIVED: 'SEPAY_WEBHOOK_RECEIVED',
  SEPAY_MONEY_IN: 'SEPAY_MONEY_IN',
  SEPAY_MONEY_OUT: 'SEPAY_MONEY_OUT',

  // Warehouse Events
  WAREHOUSE_STOCK_CREATED: 'WAREHOUSE_STOCK_CREATED',
  IMPORT_PACKAGE_CREATED: 'IMPORT_PACKAGE_CREATED',
};
