/**
 * eventTypes.js (V2)
 * Danh sách tập trung các tên Sự kiện (Domain Events) trong hệ thống
 */
module.exports = {
  // Order Domain Events
  ORDER_CREATED: "ORDER_CREATED",
  ORDER_UPDATED: "ORDER_UPDATED",
  ORDER_DELETED: "ORDER_DELETED",
  ORDER_PAID: "ORDER_PAID",
  ORDER_RENEWED: "ORDER_RENEWED",

  // Product & Pricing Domain Events
  PRODUCT_CREATED: "PRODUCT_CREATED",
  PRODUCT_UPDATED: "PRODUCT_UPDATED",
  PRODUCT_DELETED: "PRODUCT_DELETED",

  // Supplier Domain Events
  SUPPLIER_CREATED: "SUPPLIER_CREATED",
  SUPPLIER_UPDATED: "SUPPLIER_UPDATED",
  SUPPLIER_DELETED: "SUPPLIER_DELETED",
  SUPPLIER_STATUS_TOGGLED: "SUPPLIER_STATUS_TOGGLED",
  SUPPLIER_DEBT_PAID: "SUPPLIER_DEBT_PAID",

  // Supplier Cost Domain Events
  SUPPLIER_COST_ADDED: "SUPPLIER_COST_ADDED",
  SUPPLIER_COST_UPDATED: "SUPPLIER_COST_UPDATED",
  SUPPLIER_COST_DELETED: "SUPPLIER_COST_DELETED",

  // Webhook Domain Events
  WEBHOOK_MONEY_IN: "WEBHOOK_MONEY_IN",
  WEBHOOK_MONEY_OUT: "WEBHOOK_MONEY_OUT",
};


