const {
  KEY_ACTIVE_SCHEMA,
  ORDERS_SCHEMA,
  PRODUCT_SCHEMA,
  SCHEMA_KEY_ACTIVE,
  SCHEMA_ORDERS,
  SCHEMA_PRODUCT,
  tableName,
} = require("../../config/dbSchema");

const TABLES = {
  orderAutoKeys: tableName(
    KEY_ACTIVE_SCHEMA.ORDER_AUTO_KEYS.TABLE,
    SCHEMA_KEY_ACTIVE
  ),
  orderListKeys: tableName(
    KEY_ACTIVE_SCHEMA.ORDER_LIST_KEYS.TABLE,
    SCHEMA_KEY_ACTIVE
  ),
  orderList: tableName(ORDERS_SCHEMA.ORDER_LIST.TABLE, SCHEMA_ORDERS),
  variant: tableName(PRODUCT_SCHEMA.VARIANT.TABLE, SCHEMA_PRODUCT),
  systems: tableName(KEY_ACTIVE_SCHEMA.SYSTEMS.TABLE, SCHEMA_KEY_ACTIVE),
};

const COLS = {
  ORDER_AUTO_KEYS: KEY_ACTIVE_SCHEMA.ORDER_AUTO_KEYS.COLS,
  ORDER_LIST_KEYS: KEY_ACTIVE_SCHEMA.ORDER_LIST_KEYS.COLS,
  ORDER: ORDERS_SCHEMA.ORDER_LIST.COLS,
  VARIANT: PRODUCT_SCHEMA.VARIANT.COLS,
  SYSTEMS: KEY_ACTIVE_SCHEMA.SYSTEMS.COLS,
};

module.exports = {
  TABLES,
  COLS,
};

