const {
    ORDERS_SCHEMA,
    RECEIPT_SCHEMA,
    tableName,
    SCHEMA_ORDERS,
    SCHEMA_RECEIPT,
    SCHEMA_PRODUCT,
    SCHEMA_SUPPLIER,
    SCHEMA_SUPPLIER_COST,
    PRODUCT_SCHEMA,
    PARTNER_SCHEMA,
    PRICING_TIER_SCHEMA,
} = require("../../config/dbSchema");
const { STATUS } = require("../../utils/statuses");

const TABLES = {
    orderList: tableName(ORDERS_SCHEMA.ORDER_LIST.TABLE, SCHEMA_ORDERS),
    paymentReceipt: tableName(RECEIPT_SCHEMA.PAYMENT_RECEIPT.TABLE, SCHEMA_RECEIPT),
    refundCreditNotes: tableName(RECEIPT_SCHEMA.REFUND_CREDIT_NOTES.TABLE, SCHEMA_RECEIPT),
    refundCreditApplications: tableName(RECEIPT_SCHEMA.REFUND_CREDIT_APPLICATIONS.TABLE, SCHEMA_RECEIPT),
    supplier: tableName(PARTNER_SCHEMA.SUPPLIER.TABLE, SCHEMA_SUPPLIER),
    packageProduct: tableName(PRODUCT_SCHEMA.PACKAGE_PRODUCT.TABLE, SCHEMA_PRODUCT),
    supplierCost: tableName(PARTNER_SCHEMA.SUPPLIER_COST.TABLE, SCHEMA_SUPPLIER_COST),
    variant: tableName(PRODUCT_SCHEMA.VARIANT.TABLE, SCHEMA_PRODUCT),
    product: tableName(PRODUCT_SCHEMA.PRODUCT.TABLE, SCHEMA_PRODUCT),
    variantMargin: tableName(PRICING_TIER_SCHEMA.VARIANT_MARGIN.TABLE, SCHEMA_PRODUCT),
    pricingTier: tableName(PRICING_TIER_SCHEMA.PRICING_TIER.TABLE, SCHEMA_PRODUCT),
};

const COLS = {
    ORDER: ORDERS_SCHEMA.ORDER_LIST.COLS,
    SUPPLIER_COST: PARTNER_SCHEMA.SUPPLIER_COST.COLS,
    SUPPLIER: PARTNER_SCHEMA.SUPPLIER.COLS,
    VARIANT: PRODUCT_SCHEMA.VARIANT.COLS,
    PRODUCT: PRODUCT_SCHEMA.PRODUCT.COLS,
};

// Giữ nguyên trạng thái gốc (đúng với dữ liệu hiện tại)

module.exports = {
    TABLES,
    COLS,
    STATUS,
};
