const {
    ORDERS_SCHEMA,
    tableName,
    SCHEMA_ORDERS,
    SCHEMA_PRODUCT,
    SCHEMA_SUPPLIER,
    SCHEMA_SUPPLIER_COST,
    PRODUCT_SCHEMA,
    PARTNER_SCHEMA,
} = require("../../config/dbSchema");
const { STATUS } = require("../../utils/statuses");

const TABLES = {
    orderList: tableName(ORDERS_SCHEMA.ORDER_LIST.TABLE, SCHEMA_ORDERS),
    orderExpired: tableName(ORDERS_SCHEMA.ORDER_EXPIRED.TABLE, SCHEMA_ORDERS),
    orderCanceled: tableName(ORDERS_SCHEMA.ORDER_CANCELED.TABLE, SCHEMA_ORDERS),
    supplier: tableName(PARTNER_SCHEMA.SUPPLIER.TABLE, SCHEMA_SUPPLIER),
    packageProduct: tableName(PRODUCT_SCHEMA.PACKAGE_PRODUCT.TABLE, SCHEMA_PRODUCT),
    supplierCost: tableName(PARTNER_SCHEMA.SUPPLIER_COST.TABLE, SCHEMA_SUPPLIER_COST),
    variant: tableName(PRODUCT_SCHEMA.VARIANT.TABLE, SCHEMA_PRODUCT),
    priceConfig: tableName(PRODUCT_SCHEMA.PRICE_CONFIG.TABLE, SCHEMA_PRODUCT),
};

const COLS = {
    ORDER: ORDERS_SCHEMA.ORDER_LIST.COLS,
    SUPPLIER_COST: PARTNER_SCHEMA.SUPPLIER_COST.COLS,
    SUPPLIER: PARTNER_SCHEMA.SUPPLIER.COLS,
    VARIANT: PRODUCT_SCHEMA.VARIANT.COLS,
    PRICE_CONFIG: PRODUCT_SCHEMA.PRICE_CONFIG.COLS,
};

// Giữ nguyên trạng thái gốc (đúng với dữ liệu hiện tại)

module.exports = {
    TABLES,
    COLS,
    STATUS,
};
