const {
  getDefinition,
  PARTNER_SCHEMA,
  FINANCE_SCHEMA,
  SCHEMA_PARTNER,
  SCHEMA_SUPPLIER,
  SCHEMA_ORDERS,
  SCHEMA_RECEIPT,
  SCHEMA_FINANCE,
  ORDERS_SCHEMA,
  RECEIPT_SCHEMA,
  tableName,
} = require("../../../config/dbSchema");
const { QUOTED_COLS } = require("../../../utils/columns");

const PAYMENT_RECEIPT_DEF = getDefinition("PAYMENT_RECEIPT", RECEIPT_SCHEMA);
const PAYMENT_RECEIPT_STATE_DEF = getDefinition(
  "PAYMENT_RECEIPT_FINANCIAL_STATE",
  RECEIPT_SCHEMA
);
const PAYMENT_RECEIPT_AUDIT_DEF = getDefinition(
  "PAYMENT_RECEIPT_FINANCIAL_AUDIT_LOG",
  RECEIPT_SCHEMA
);
const ORDER_LIST_DEF = getDefinition("ORDER_LIST", ORDERS_SCHEMA);
const DASHBOARD_SUMMARY_DEF = getDefinition(
  "DASHBOARD_MONTHLY_SUMMARY",
  FINANCE_SCHEMA
);
const PAYMENT_SUPPLY_DEF = getDefinition("PAYMENT_SUPPLY", PARTNER_SCHEMA);

const PAYMENT_RECEIPT_BATCH_COLS = RECEIPT_SCHEMA.PAYMENT_RECEIPT_BATCH.COLS;
const PAYMENT_RECEIPT_BATCH_ITEM_COLS = RECEIPT_SCHEMA.PAYMENT_RECEIPT_BATCH_ITEM.COLS;

const TABLES = {
  paymentReceipt: tableName(PAYMENT_RECEIPT_DEF.tableName, SCHEMA_RECEIPT),
  paymentReceiptState: tableName(PAYMENT_RECEIPT_STATE_DEF.tableName, SCHEMA_RECEIPT),
  paymentReceiptAudit: tableName(PAYMENT_RECEIPT_AUDIT_DEF.tableName, SCHEMA_RECEIPT),
  orderList: tableName(ORDER_LIST_DEF.tableName, SCHEMA_ORDERS),
  dashboardSummary: tableName(DASHBOARD_SUMMARY_DEF.tableName, SCHEMA_FINANCE),
  paymentSupply: tableName(PAYMENT_SUPPLY_DEF.tableName, SCHEMA_PARTNER),
  paymentReceiptBatch: tableName(RECEIPT_SCHEMA.PAYMENT_RECEIPT_BATCH.TABLE, SCHEMA_RECEIPT),
  paymentReceiptBatchItem: tableName(RECEIPT_SCHEMA.PAYMENT_RECEIPT_BATCH_ITEM.TABLE, SCHEMA_RECEIPT),
  supply: tableName(PARTNER_SCHEMA.SUPPLIER.TABLE, SCHEMA_SUPPLIER),
  supplyOrderCostLog: tableName(PARTNER_SCHEMA.SUPPLIER_ORDER_COST_LOG.TABLE, SCHEMA_PARTNER),
};

const PS = QUOTED_COLS.paymentSupply;
const RECEIPT_STATE_COLS = PAYMENT_RECEIPT_STATE_DEF.columns;
const ORDER_COLS = ORDER_LIST_DEF.columns;
const SUMMARY_COLS = DASHBOARD_SUMMARY_DEF.columns;

const RECONCILE_ACTIONS = {
  ONLY: "reconcile_only",
  MARK_PAID: "reconcile_and_mark_paid",
  RENEW: "reconcile_and_renew",
};
const SUPPORTED_RECONCILE_ACTIONS = new Set([
  RECONCILE_ACTIONS.ONLY,
  RECONCILE_ACTIONS.MARK_PAID,
  RECONCILE_ACTIONS.RENEW,
]);

const ORDER_CODE_REGEX_GLOBAL = /\bMAV[A-Z0-9]{3,20}\b/gi;
const BATCH_CODE_REGEX_STRICT = /^MAVG[A-Z0-9]{4,20}$/i;
const BATCH_CODE_PREFIX = "MAVG";

module.exports = {
  PAYMENT_RECEIPT_DEF,
  PAYMENT_RECEIPT_STATE_DEF,
  PAYMENT_RECEIPT_AUDIT_DEF,
  ORDER_LIST_DEF,
  DASHBOARD_SUMMARY_DEF,
  PAYMENT_SUPPLY_DEF,
  PAYMENT_RECEIPT_BATCH_COLS,
  PAYMENT_RECEIPT_BATCH_ITEM_COLS,
  TABLES,
  PS,
  RECEIPT_STATE_COLS,
  ORDER_COLS,
  SUMMARY_COLS,
  SCHEMA_PARTNER,
  RECONCILE_ACTIONS,
  SUPPORTED_RECONCILE_ACTIONS,
  ORDER_CODE_REGEX_GLOBAL,
  BATCH_CODE_REGEX_STRICT,
  BATCH_CODE_PREFIX,
};
