const {
  SCHEMA_ORDERS,
  SCHEMA_PRODUCT,
  SCHEMA_PARTNER,
  SCHEMA_ADMIN,
  SCHEMA_FINANCE,
  SCHEMA_IDENTITY,
  SCHEMA_CUSTOMER_PROFILES,
  SCHEMA_MAIL_BACKUP,
  SCHEMA_COMMON,
  SCHEMA_PROMOTION,
  SCHEMA_WALLET,
  SCHEMA_FORM_DESC,
  SCHEMA_RENEW_ADOBE,
  SCHEMA_KEY_ACTIVE,
  SCHEMA_INPUTS,
  SCHEMA_SUPPLIER,
  SCHEMA_SUPPLIER_COST,
  NOTIFICATION_GROUP_ID,
  RENEWAL_TOPIC_ID,
} = require("./dbSchema/env");
const {
  tableName,
  getTable,
  getColumns,
  getDefinition,
} = require("./dbSchema/helpers");
const { ADMIN_SCHEMA, FINANCE_SCHEMA } = require("./dbSchema/schemas/adminFinance");
const {
  FORM_DESC_SCHEMA,
  IDENTITY_SCHEMA,
  COMMON_SCHEMA,
} = require("./dbSchema/schemas/formsIdentity");
const {
  PROMOTION_SCHEMA,
  WALLET_SCHEMA,
} = require("./dbSchema/schemas/promotionWallet");
const {
  ORDERS_SCHEMA,
  PRODUCT_SCHEMA,
  PARTNER_SCHEMA,
} = require("./dbSchema/schemas/ordersProductPartner");
const {
  RENEW_ADOBE_SCHEMA,
  KEY_ACTIVE_SCHEMA,
} = require("./dbSchema/schemas/automation");

module.exports = {
  SCHEMA_ORDERS,
  SCHEMA_PRODUCT,
  SCHEMA_ADMIN,
  SCHEMA_IDENTITY,
  SCHEMA_CUSTOMER_PROFILES,
  SCHEMA_MAIL_BACKUP,
  SCHEMA_COMMON,
  SCHEMA_PROMOTION,
  SCHEMA_WALLET,
  SCHEMA_FORM_DESC,
  SCHEMA_INPUTS,
  SCHEMA_FINANCE,
  SCHEMA_SUPPLIER,
  SCHEMA_SUPPLIER_COST,
  SCHEMA_RENEW_ADOBE,
  SCHEMA_KEY_ACTIVE,
  NOTIFICATION_GROUP_ID,
  RENEWAL_TOPIC_ID,
  tableName,
  getTable,
  getColumns,
  getDefinition,
  ADMIN_SCHEMA,
  FINANCE_SCHEMA,
  COMMON_SCHEMA,
  IDENTITY_SCHEMA,
  PROMOTION_SCHEMA,
  WALLET_SCHEMA,
  FORM_DESC_SCHEMA,
  ORDERS_SCHEMA,
  PRODUCT_SCHEMA,
  SCHEMA_PARTNER,
  PARTNER_SCHEMA,
  RENEW_ADOBE_SCHEMA,
  KEY_ACTIVE_SCHEMA,
};
